# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tabbed.ui'
#
# Created: Sat Jan  2 00:33:30 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_LWCAttendanceTaker(object):
    def setupUi(self, LWCAttendanceTaker):
        LWCAttendanceTaker.setObjectName("LWCAttendanceTaker")
        LWCAttendanceTaker.resize(1200, 743)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LWCAttendanceTaker.sizePolicy().hasHeightForWidth())
        LWCAttendanceTaker.setSizePolicy(sizePolicy)
        LWCAttendanceTaker.setMinimumSize(QtCore.QSize(1200, 0))
        LWCAttendanceTaker.setWindowOpacity(1.0)
        LWCAttendanceTaker.setAutoFillBackground(False)
        LWCAttendanceTaker.setStyleSheet("")
        LWCAttendanceTaker.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(LWCAttendanceTaker)
        self.centralwidget.setObjectName("centralwidget")
        self.tab_widget_overall = QtGui.QTabWidget(self.centralwidget)
        self.tab_widget_overall.setGeometry(QtCore.QRect(10, 10, 1181, 651))
        self.tab_widget_overall.setIconSize(QtCore.QSize(25, 25))
        self.tab_widget_overall.setObjectName("tab_widget_overall")
        self.tab_setup = QtGui.QWidget()
        self.tab_setup.setObjectName("tab_setup")
        self.verticalLayoutWidget = QtGui.QWidget(self.tab_setup)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 393, 351))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtGui.QGroupBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox_serialPort = QtGui.QComboBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox_serialPort.setFont(font)
        self.comboBox_serialPort.setObjectName("comboBox_serialPort")
        self.verticalLayout.addWidget(self.comboBox_serialPort)
        self.pushButton_refresh = QtGui.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.pushButton_refresh.setFont(font)
        self.pushButton_refresh.setObjectName("pushButton_refresh")
        self.verticalLayout.addWidget(self.pushButton_refresh)
        self.pushButton_connect = QtGui.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.pushButton_connect.setFont(font)
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.verticalLayout.addWidget(self.pushButton_connect)
        self.pushButton_disconnect = QtGui.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.pushButton_disconnect.setFont(font)
        self.pushButton_disconnect.setObjectName("pushButton_disconnect")
        self.verticalLayout.addWidget(self.pushButton_disconnect)
        self.horizontalLayout_8.addLayout(self.verticalLayout)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_5 = QtGui.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_19 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.pushButton_dbconnect = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_dbconnect.setObjectName("pushButton_dbconnect")
        self.gridLayout_19.addWidget(self.pushButton_dbconnect, 1, 0, 1, 1)
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName("formLayout_3")
        self.databaseHostLabel = QtGui.QLabel(self.groupBox_5)
        self.databaseHostLabel.setObjectName("databaseHostLabel")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.databaseHostLabel)
        self.databaseHostLineEdit = QtGui.QLineEdit(self.groupBox_5)
        self.databaseHostLineEdit.setObjectName("databaseHostLineEdit")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.databaseHostLineEdit)
        self.gridLayout_19.addLayout(self.formLayout_3, 0, 0, 1, 1)
        self.pushButton_connecttohome = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_connecttohome.setObjectName("pushButton_connecttohome")
        self.gridLayout_19.addWidget(self.pushButton_connecttohome, 2, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_5)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tab_widget_overall.addTab(self.tab_setup, icon, "")
        self.tab_attendance = QtGui.QWidget()
        self.tab_attendance.setObjectName("tab_attendance")
        self.label_welcome = QtGui.QLabel(self.tab_attendance)
        self.label_welcome.setGeometry(QtCore.QRect(10, 9, 1061, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_welcome.sizePolicy().hasHeightForWidth())
        self.label_welcome.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(75)
        font.setBold(True)
        self.label_welcome.setFont(font)
        self.label_welcome.setAlignment(QtCore.Qt.AlignCenter)
        self.label_welcome.setObjectName("label_welcome")
        self.groupBox_2 = QtGui.QGroupBox(self.tab_attendance)
        self.groupBox_2.setGeometry(QtCore.QRect(380, 60, 491, 211))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setCursor(QtCore.Qt.ArrowCursor)
        self.groupBox_2.setStyleSheet("background-color: rgba(255, 255, 255, 150)")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_picture = QtGui.QLabel(self.groupBox_2)
        self.label_picture.setGeometry(QtCore.QRect(320, 20, 160, 160))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_picture.sizePolicy().hasHeightForWidth())
        self.label_picture.setSizePolicy(sizePolicy)
        self.label_picture.setMinimumSize(QtCore.QSize(160, 160))
        self.label_picture.setStyleSheet("background-color: rgba(255, 255, 255, 0)")
        self.label_picture.setText("")
        self.label_picture.setObjectName("label_picture")
        self.label_static_name = QtGui.QLabel(self.groupBox_2)
        self.label_static_name.setGeometry(QtCore.QRect(23, 26, 45, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.label_static_name.setFont(font)
        self.label_static_name.setStyleSheet("background-color: rgba(255, 255, 255, 0)")
        self.label_static_name.setObjectName("label_static_name")
        self.label_dynamic_engname = QtGui.QLabel(self.groupBox_2)
        self.label_dynamic_engname.setGeometry(QtCore.QRect(74, 57, 241, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setWeight(50)
        font.setBold(False)
        self.label_dynamic_engname.setFont(font)
        self.label_dynamic_engname.setStyleSheet("background-color: rgba(255, 255, 255, 0)")
        self.label_dynamic_engname.setText("")
        self.label_dynamic_engname.setWordWrap(True)
        self.label_dynamic_engname.setObjectName("label_dynamic_engname")
        self.label_dynamic_name = QtGui.QLabel(self.groupBox_2)
        self.label_dynamic_name.setGeometry(QtCore.QRect(74, 26, 241, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(50)
        font.setBold(False)
        self.label_dynamic_name.setFont(font)
        self.label_dynamic_name.setCursor(QtCore.Qt.IBeamCursor)
        self.label_dynamic_name.setStyleSheet("background-color: rgba(255, 255, 255, 0)")
        self.label_dynamic_name.setText("")
        self.label_dynamic_name.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_dynamic_name.setObjectName("label_dynamic_name")
        self.label_static_dummy = QtGui.QLabel(self.groupBox_2)
        self.label_static_dummy.setGeometry(QtCore.QRect(58, 57, 16, 17))
        self.label_static_dummy.setStyleSheet("background-color: rgba(255, 255, 255, 0)")
        self.label_static_dummy.setText("")
        self.label_static_dummy.setObjectName("label_static_dummy")
        self.label_static_rfid = QtGui.QLabel(self.groupBox_2)
        self.label_static_rfid.setGeometry(QtCore.QRect(29, 83, 39, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.label_static_rfid.setFont(font)
        self.label_static_rfid.setStyleSheet("background-color: rgba(255, 255, 255, 0)")
        self.label_static_rfid.setObjectName("label_static_rfid")
        self.label_dynamic_rfid = QtGui.QLabel(self.groupBox_2)
        self.label_dynamic_rfid.setGeometry(QtCore.QRect(74, 83, 241, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.label_dynamic_rfid.setFont(font)
        self.label_dynamic_rfid.setCursor(QtCore.Qt.IBeamCursor)
        self.label_dynamic_rfid.setStyleSheet("background-color: rgba(255, 255, 255, 0)\n"
"")
        self.label_dynamic_rfid.setText("")
        self.label_dynamic_rfid.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_dynamic_rfid.setObjectName("label_dynamic_rfid")
        self.label_static_dept = QtGui.QLabel(self.groupBox_2)
        self.label_static_dept.setGeometry(QtCore.QRect(28, 106, 40, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.label_static_dept.setFont(font)
        self.label_static_dept.setStyleSheet("background-color: rgba(255, 255, 255, 0)")
        self.label_static_dept.setObjectName("label_static_dept")
        self.label_dynamic_dept = QtGui.QLabel(self.groupBox_2)
        self.label_dynamic_dept.setGeometry(QtCore.QRect(74, 106, 241, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.label_dynamic_dept.setFont(font)
        self.label_dynamic_dept.setStyleSheet("background-color: rgba(255, 255, 255, 0)")
        self.label_dynamic_dept.setText("")
        self.label_dynamic_dept.setObjectName("label_dynamic_dept")
        self.label_static_status = QtGui.QLabel(self.groupBox_2)
        self.label_static_status.setGeometry(QtCore.QRect(18, 129, 50, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.label_static_status.setFont(font)
        self.label_static_status.setStyleSheet("background-color: rgba(255, 255, 255, 0)")
        self.label_static_status.setObjectName("label_static_status")
        self.label_dynamic_status = QtGui.QLabel(self.groupBox_2)
        self.label_dynamic_status.setGeometry(QtCore.QRect(74, 129, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.label_dynamic_status.setFont(font)
        self.label_dynamic_status.setCursor(QtCore.Qt.IBeamCursor)
        self.label_dynamic_status.setStyleSheet("background-color: rgba(255, 255, 255, 0)")
        self.label_dynamic_status.setText("")
        self.label_dynamic_status.setScaledContents(False)
        self.label_dynamic_status.setWordWrap(True)
        self.label_dynamic_status.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_dynamic_status.setObjectName("label_dynamic_status")
        self.groupBox_4 = QtGui.QGroupBox(self.tab_attendance)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 60, 331, 211))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setAutoFillBackground(False)
        self.groupBox_4.setStyleSheet("background-color: rgba(255, 255, 255, 150)")
        self.groupBox_4.setCheckable(False)
        self.groupBox_4.setObjectName("groupBox_4")
        self.layoutWidget = QtGui.QWidget(self.groupBox_4)
        self.layoutWidget.setGeometry(QtCore.QRect(7, 22, 321, 601))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout_2 = QtGui.QFormLayout(self.layoutWidget)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_static_time = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.label_static_time.setFont(font)
        self.label_static_time.setStyleSheet("background-color: rgba(255, 255, 255, 0)")
        self.label_static_time.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_static_time.setObjectName("label_static_time")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_static_time)
        self.lcdNumber_time = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdNumber_time.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lcdNumber_time.setFont(font)
        self.lcdNumber_time.setStyleSheet("QLCDNumber{\n"
"    color:rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 127);\n"
"}")
        self.lcdNumber_time.setObjectName("lcdNumber_time")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.lcdNumber_time)
        self.label_static_date = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.label_static_date.setFont(font)
        self.label_static_date.setStyleSheet("background-color: rgba(255, 255, 255, 0)")
        self.label_static_date.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_static_date.setObjectName("label_static_date")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_static_date)
        self.label_dynamic_date = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.label_dynamic_date.setFont(font)
        self.label_dynamic_date.setStyleSheet("background-color: rgba(255, 255, 255, 0)")
        self.label_dynamic_date.setText("")
        self.label_dynamic_date.setObjectName("label_dynamic_date")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.label_dynamic_date)
        self.label_static_event = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.label_static_event.setFont(font)
        self.label_static_event.setStyleSheet("background-color: rgba(255, 255, 255, 0)")
        self.label_static_event.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_static_event.setObjectName("label_static_event")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_static_event)
        self.label_dynamic_event = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_dynamic_event.sizePolicy().hasHeightForWidth())
        self.label_dynamic_event.setSizePolicy(sizePolicy)
        self.label_dynamic_event.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(50)
        font.setBold(False)
        self.label_dynamic_event.setFont(font)
        self.label_dynamic_event.setStyleSheet("background-color: rgba(255, 255, 255, 0)")
        self.label_dynamic_event.setText("")
        self.label_dynamic_event.setWordWrap(True)
        self.label_dynamic_event.setObjectName("label_dynamic_event")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.label_dynamic_event)
        self.backgroundpic = QtGui.QLabel(self.tab_attendance)
        self.backgroundpic.setGeometry(QtCore.QRect(-90, 0, 1301, 721))
        self.backgroundpic.setStyleSheet("")
        self.backgroundpic.setText("")
        self.backgroundpic.setPixmap(QtGui.QPixmap("icon/1920X1280-chi.jpg"))
        self.backgroundpic.setObjectName("backgroundpic")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/Workers.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tab_widget_overall.addTab(self.tab_attendance, icon1, "")
        self.tab_statistics = QtGui.QWidget()
        self.tab_statistics.setObjectName("tab_statistics")
        self.gridLayout_9 = QtGui.QGridLayout(self.tab_statistics)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.tabWidget_statistics = QtGui.QTabWidget(self.tab_statistics)
        self.tabWidget_statistics.setObjectName("tabWidget_statistics")
        self.tab_sundayservice = QtGui.QWidget()
        self.tab_sundayservice.setObjectName("tab_sundayservice")
        self.gridLayout_12 = QtGui.QGridLayout(self.tab_sundayservice)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.stackedWidget_ss = QtGui.QStackedWidget(self.tab_sundayservice)
        self.stackedWidget_ss.setObjectName("stackedWidget_ss")
        self.page_6 = QtGui.QWidget()
        self.page_6.setObjectName("page_6")
        self.gridLayout_31 = QtGui.QGridLayout(self.page_6)
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.mpl_sundayservicestats = MplWidget(self.page_6)
        self.mpl_sundayservicestats.setObjectName("mpl_sundayservicestats")
        self.gridLayout_31.addWidget(self.mpl_sundayservicestats, 0, 0, 1, 1)
        self.stackedWidget_ss.addWidget(self.page_6)
        self.page_7 = QtGui.QWidget()
        self.page_7.setObjectName("page_7")
        self.gridLayout_24 = QtGui.QGridLayout(self.page_7)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.mpl_sundayservice_daily = MplWidget(self.page_7)
        self.mpl_sundayservice_daily.setObjectName("mpl_sundayservice_daily")
        self.gridLayout_24.addWidget(self.mpl_sundayservice_daily, 0, 0, 1, 1)
        self.stackedWidget_ss.addWidget(self.page_7)
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_10 = QtGui.QGridLayout(self.page)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.mpl_sundayservicedeptstats = MplWidget(self.page)
        self.mpl_sundayservicedeptstats.setObjectName("mpl_sundayservicedeptstats")
        self.gridLayout_10.addWidget(self.mpl_sundayservicedeptstats, 0, 0, 1, 1)
        self.stackedWidget_ss.addWidget(self.page)
        self.horizontalLayout_3.addWidget(self.stackedWidget_ss)
        self.gridLayout_12.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem)
        self.pushButton_previous_graph_ss = QtGui.QPushButton(self.tab_sundayservice)
        self.pushButton_previous_graph_ss.setObjectName("pushButton_previous_graph_ss")
        self.horizontalLayout_12.addWidget(self.pushButton_previous_graph_ss)
        self.pushButton_next_graph_ss = QtGui.QPushButton(self.tab_sundayservice)
        self.pushButton_next_graph_ss.setObjectName("pushButton_next_graph_ss")
        self.horizontalLayout_12.addWidget(self.pushButton_next_graph_ss)
        self.gridLayout_12.addLayout(self.horizontalLayout_12, 0, 0, 1, 1)
        self.tabWidget_statistics.addTab(self.tab_sundayservice, "")
        self.tab_wednesdayservice = QtGui.QWidget()
        self.tab_wednesdayservice.setObjectName("tab_wednesdayservice")
        self.gridLayout_14 = QtGui.QGridLayout(self.tab_wednesdayservice)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.stackedWidget_ws = QtGui.QStackedWidget(self.tab_wednesdayservice)
        self.stackedWidget_ws.setObjectName("stackedWidget_ws")
        self.page_8 = QtGui.QWidget()
        self.page_8.setObjectName("page_8")
        self.gridLayout_29 = QtGui.QGridLayout(self.page_8)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.mpl_weddayservicestats = MplWidget(self.page_8)
        self.mpl_weddayservicestats.setObjectName("mpl_weddayservicestats")
        self.gridLayout_29.addWidget(self.mpl_weddayservicestats, 0, 0, 1, 1)
        self.stackedWidget_ws.addWidget(self.page_8)
        self.page_9 = QtGui.QWidget()
        self.page_9.setObjectName("page_9")
        self.gridLayout_25 = QtGui.QGridLayout(self.page_9)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.mpl_wednesdayservice_daily = MplWidget(self.page_9)
        self.mpl_wednesdayservice_daily.setObjectName("mpl_wednesdayservice_daily")
        self.gridLayout_25.addWidget(self.mpl_wednesdayservice_daily, 0, 0, 1, 1)
        self.stackedWidget_ws.addWidget(self.page_9)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_21 = QtGui.QGridLayout(self.page_2)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.mpl_weddayservicedeptstats = MplWidget(self.page_2)
        self.mpl_weddayservicedeptstats.setObjectName("mpl_weddayservicedeptstats")
        self.gridLayout_21.addWidget(self.mpl_weddayservicedeptstats, 0, 0, 1, 1)
        self.stackedWidget_ws.addWidget(self.page_2)
        self.horizontalLayout_4.addWidget(self.stackedWidget_ws)
        self.gridLayout_14.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem1)
        self.pushButton_previous_graph_ws = QtGui.QPushButton(self.tab_wednesdayservice)
        self.pushButton_previous_graph_ws.setObjectName("pushButton_previous_graph_ws")
        self.horizontalLayout_13.addWidget(self.pushButton_previous_graph_ws)
        self.pushButton_next_graph_ws = QtGui.QPushButton(self.tab_wednesdayservice)
        self.pushButton_next_graph_ws.setObjectName("pushButton_next_graph_ws")
        self.horizontalLayout_13.addWidget(self.pushButton_next_graph_ws)
        self.gridLayout_14.addLayout(self.horizontalLayout_13, 0, 0, 1, 1)
        self.tabWidget_statistics.addTab(self.tab_wednesdayservice, "")
        self.tab_fridayprayer = QtGui.QWidget()
        self.tab_fridayprayer.setObjectName("tab_fridayprayer")
        self.gridLayout_16 = QtGui.QGridLayout(self.tab_fridayprayer)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.stackedWidget_fpm = QtGui.QStackedWidget(self.tab_fridayprayer)
        self.stackedWidget_fpm.setObjectName("stackedWidget_fpm")
        self.page_10 = QtGui.QWidget()
        self.page_10.setObjectName("page_10")
        self.gridLayout_30 = QtGui.QGridLayout(self.page_10)
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.mpl_fridayservicestats = MplWidget(self.page_10)
        self.mpl_fridayservicestats.setObjectName("mpl_fridayservicestats")
        self.gridLayout_30.addWidget(self.mpl_fridayservicestats, 0, 0, 1, 1)
        self.stackedWidget_fpm.addWidget(self.page_10)
        self.page_11 = QtGui.QWidget()
        self.page_11.setObjectName("page_11")
        self.gridLayout_26 = QtGui.QGridLayout(self.page_11)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.mpl_fridayprayer_daily = MplWidget(self.page_11)
        self.mpl_fridayprayer_daily.setObjectName("mpl_fridayprayer_daily")
        self.gridLayout_26.addWidget(self.mpl_fridayprayer_daily, 0, 0, 1, 1)
        self.stackedWidget_fpm.addWidget(self.page_11)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_22 = QtGui.QGridLayout(self.page_3)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.mpl_fridayservicedeptstats = MplWidget(self.page_3)
        self.mpl_fridayservicedeptstats.setObjectName("mpl_fridayservicedeptstats")
        self.gridLayout_22.addWidget(self.mpl_fridayservicedeptstats, 0, 0, 1, 1)
        self.stackedWidget_fpm.addWidget(self.page_3)
        self.horizontalLayout_5.addWidget(self.stackedWidget_fpm)
        self.gridLayout_16.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem2)
        self.pushButton_previous_graph_fpm = QtGui.QPushButton(self.tab_fridayprayer)
        self.pushButton_previous_graph_fpm.setObjectName("pushButton_previous_graph_fpm")
        self.horizontalLayout_14.addWidget(self.pushButton_previous_graph_fpm)
        self.pushButton_next_graph_fpm = QtGui.QPushButton(self.tab_fridayprayer)
        self.pushButton_next_graph_fpm.setObjectName("pushButton_next_graph_fpm")
        self.horizontalLayout_14.addWidget(self.pushButton_next_graph_fpm)
        self.gridLayout_16.addLayout(self.horizontalLayout_14, 0, 0, 1, 1)
        self.tabWidget_statistics.addTab(self.tab_fridayprayer, "")
        self.tab_dawnservice = QtGui.QWidget()
        self.tab_dawnservice.setObjectName("tab_dawnservice")
        self.gridLayout_18 = QtGui.QGridLayout(self.tab_dawnservice)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.stackedWidget_ds = QtGui.QStackedWidget(self.tab_dawnservice)
        self.stackedWidget_ds.setObjectName("stackedWidget_ds")
        self.page_12 = QtGui.QWidget()
        self.page_12.setObjectName("page_12")
        self.gridLayout_28 = QtGui.QGridLayout(self.page_12)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.mpl_dawnservicestats = MplWidget(self.page_12)
        self.mpl_dawnservicestats.setObjectName("mpl_dawnservicestats")
        self.gridLayout_28.addWidget(self.mpl_dawnservicestats, 0, 0, 1, 1)
        self.stackedWidget_ds.addWidget(self.page_12)
        self.page_13 = QtGui.QWidget()
        self.page_13.setObjectName("page_13")
        self.gridLayout_27 = QtGui.QGridLayout(self.page_13)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.mpl_dawnservice_daily = MplWidget(self.page_13)
        self.mpl_dawnservice_daily.setObjectName("mpl_dawnservice_daily")
        self.gridLayout_27.addWidget(self.mpl_dawnservice_daily, 0, 0, 1, 1)
        self.stackedWidget_ds.addWidget(self.page_13)
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_23 = QtGui.QGridLayout(self.page_4)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.mpl_dawnservicedeptstats = MplWidget(self.page_4)
        self.mpl_dawnservicedeptstats.setObjectName("mpl_dawnservicedeptstats")
        self.gridLayout_23.addWidget(self.mpl_dawnservicedeptstats, 0, 0, 1, 1)
        self.stackedWidget_ds.addWidget(self.page_4)
        self.horizontalLayout_6.addWidget(self.stackedWidget_ds)
        self.gridLayout_18.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem3)
        self.pushButton_previous_graph_ds = QtGui.QPushButton(self.tab_dawnservice)
        self.pushButton_previous_graph_ds.setObjectName("pushButton_previous_graph_ds")
        self.horizontalLayout_15.addWidget(self.pushButton_previous_graph_ds)
        self.pushButton_next_graph_ds = QtGui.QPushButton(self.tab_dawnservice)
        self.pushButton_next_graph_ds.setObjectName("pushButton_next_graph_ds")
        self.horizontalLayout_15.addWidget(self.pushButton_next_graph_ds)
        self.gridLayout_18.addLayout(self.horizontalLayout_15, 0, 0, 1, 1)
        self.tabWidget_statistics.addTab(self.tab_dawnservice, "")
        self.gridLayout_8.addWidget(self.tabWidget_statistics, 0, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.label_2 = QtGui.QLabel(self.tab_statistics)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.comboBox_monthselector = QtGui.QComboBox(self.tab_statistics)
        self.comboBox_monthselector.setObjectName("comboBox_monthselector")
        self.horizontalLayout_2.addWidget(self.comboBox_monthselector)
        self.label_3 = QtGui.QLabel(self.tab_statistics)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.comboBox_yearselector = QtGui.QComboBox(self.tab_statistics)
        self.comboBox_yearselector.setObjectName("comboBox_yearselector")
        self.horizontalLayout_2.addWidget(self.comboBox_yearselector)
        self.pushButton_plot = QtGui.QPushButton(self.tab_statistics)
        self.pushButton_plot.setObjectName("pushButton_plot")
        self.horizontalLayout_2.addWidget(self.pushButton_plot)
        self.gridLayout_9.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/Graph.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tab_widget_overall.addTab(self.tab_statistics, icon2, "")
        self.tab_admin = QtGui.QWidget()
        self.tab_admin.setObjectName("tab_admin")
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_admin)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tabWidget_adminmarking = QtGui.QTabWidget(self.tab_admin)
        self.tabWidget_adminmarking.setMovable(False)
        self.tabWidget_adminmarking.setObjectName("tabWidget_adminmarking")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.tab_5)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.groupBox_3 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName("gridLayout")
        self.label_admintab_dept = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_admintab_dept.setFont(font)
        self.label_admintab_dept.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_admintab_dept.setObjectName("label_admintab_dept")
        self.gridLayout.addWidget(self.label_admintab_dept, 0, 0, 1, 1)
        self.comboBox_admintab_dept = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_admintab_dept.setObjectName("comboBox_admintab_dept")
        self.gridLayout.addWidget(self.comboBox_admintab_dept, 0, 2, 1, 1)
        self.label_admintab_name = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_admintab_name.setFont(font)
        self.label_admintab_name.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_admintab_name.setObjectName("label_admintab_name")
        self.gridLayout.addWidget(self.label_admintab_name, 1, 0, 1, 1)
        self.comboBox_admintab_name = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_admintab_name.setObjectName("comboBox_admintab_name")
        self.gridLayout.addWidget(self.comboBox_admintab_name, 1, 2, 1, 1)
        self.label_admintab_event = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_admintab_event.setFont(font)
        self.label_admintab_event.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_admintab_event.setObjectName("label_admintab_event")
        self.gridLayout.addWidget(self.label_admintab_event, 3, 0, 1, 1)
        self.comboBox_admintab_event = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_admintab_event.setObjectName("comboBox_admintab_event")
        self.gridLayout.addWidget(self.comboBox_admintab_event, 3, 2, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 0, 1, 1)
        self.calendarWidget = QtGui.QCalendarWidget(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calendarWidget.sizePolicy().hasHeightForWidth())
        self.calendarWidget.setSizePolicy(sizePolicy)
        self.calendarWidget.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.calendarWidget.setFont(font)
        self.calendarWidget.setCursor(QtCore.Qt.PointingHandCursor)
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setVerticalHeaderFormat(QtGui.QCalendarWidget.NoVerticalHeader)
        self.calendarWidget.setNavigationBarVisible(True)
        self.calendarWidget.setDateEditEnabled(True)
        self.calendarWidget.setObjectName("calendarWidget")
        self.gridLayout.addWidget(self.calendarWidget, 4, 2, 1, 1)
        self.label_admintab_status = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_admintab_status.setFont(font)
        self.label_admintab_status.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_admintab_status.setObjectName("label_admintab_status")
        self.gridLayout.addWidget(self.label_admintab_status, 5, 0, 1, 1)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.pushButton_delete = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.horizontalLayout_16.addWidget(self.pushButton_delete)
        self.pushButton_submit = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_submit.setObjectName("pushButton_submit")
        self.horizontalLayout_16.addWidget(self.pushButton_submit)
        self.gridLayout.addLayout(self.horizontalLayout_16, 9, 2, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 8, 2, 1, 1)
        self.label_attmarkingpic = QtGui.QLabel(self.groupBox_3)
        self.label_attmarkingpic.setText("")
        self.label_attmarkingpic.setPixmap(QtGui.QPixmap("icon/unknown_profile.png"))
        self.label_attmarkingpic.setAlignment(QtCore.Qt.AlignCenter)
        self.label_attmarkingpic.setObjectName("label_attmarkingpic")
        self.gridLayout.addWidget(self.label_attmarkingpic, 2, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.radioButton_broadcast = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_broadcast.setObjectName("radioButton_broadcast")
        self.gridLayout.addWidget(self.radioButton_broadcast, 7, 2, 1, 1)
        self.radioButton_present = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_present.setObjectName("radioButton_present")
        self.gridLayout.addWidget(self.radioButton_present, 5, 2, 1, 1)
        self.horizontalLayout_11.addWidget(self.groupBox_3)
        self.groupBox_8 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.attendeeLabel = QtGui.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.attendeeLabel.setFont(font)
        self.attendeeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.attendeeLabel.setObjectName("attendeeLabel")
        self.gridLayout_2.addWidget(self.attendeeLabel, 4, 0, 1, 1)
        self.eventLabel = QtGui.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.eventLabel.setFont(font)
        self.eventLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.eventLabel.setObjectName("eventLabel")
        self.gridLayout_2.addWidget(self.eventLabel, 2, 0, 1, 1)
        self.dateLabel = QtGui.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.dateLabel.setFont(font)
        self.dateLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dateLabel.setObjectName("dateLabel")
        self.gridLayout_2.addWidget(self.dateLabel, 0, 0, 1, 1)
        self.tableWidget_attendee = QtGui.QTableWidget(self.groupBox_8)
        self.tableWidget_attendee.setObjectName("tableWidget_attendee")
        self.tableWidget_attendee.setColumnCount(0)
        self.tableWidget_attendee.setRowCount(0)
        self.gridLayout_2.addWidget(self.tableWidget_attendee, 4, 1, 1, 1)
        self.pushButton_viewatt = QtGui.QPushButton(self.groupBox_8)
        self.pushButton_viewatt.setObjectName("pushButton_viewatt")
        self.gridLayout_2.addWidget(self.pushButton_viewatt, 5, 1, 1, 1)
        self.comboBox_eventviewatt = QtGui.QComboBox(self.groupBox_8)
        self.comboBox_eventviewatt.setObjectName("comboBox_eventviewatt")
        self.gridLayout_2.addWidget(self.comboBox_eventviewatt, 2, 1, 1, 1)
        self.calendarWidget_attview = QtGui.QCalendarWidget(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calendarWidget_attview.sizePolicy().hasHeightForWidth())
        self.calendarWidget_attview.setSizePolicy(sizePolicy)
        self.calendarWidget_attview.setMinimumSize(QtCore.QSize(0, 0))
        self.calendarWidget_attview.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.calendarWidget_attview.setFont(font)
        self.calendarWidget_attview.setCursor(QtCore.Qt.PointingHandCursor)
        self.calendarWidget_attview.setGridVisible(True)
        self.calendarWidget_attview.setVerticalHeaderFormat(QtGui.QCalendarWidget.NoVerticalHeader)
        self.calendarWidget_attview.setObjectName("calendarWidget_attview")
        self.gridLayout_2.addWidget(self.calendarWidget_attview, 0, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 6, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_21 = QtGui.QLabel(self.groupBox_8)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 1, 0, 1, 1)
        self.label_20 = QtGui.QLabel(self.groupBox_8)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 0, 0, 1, 1)
        self.label_totalpresent = QtGui.QLabel(self.groupBox_8)
        self.label_totalpresent.setText("")
        self.label_totalpresent.setObjectName("label_totalpresent")
        self.gridLayout_3.addWidget(self.label_totalpresent, 0, 1, 1, 1)
        self.label_totalbroadcast = QtGui.QLabel(self.groupBox_8)
        self.label_totalbroadcast.setText("")
        self.label_totalbroadcast.setObjectName("label_totalbroadcast")
        self.gridLayout_3.addWidget(self.label_totalbroadcast, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 6, 1, 1, 1)
        self.horizontalLayout_11.addWidget(self.groupBox_8)
        self.tabWidget_adminmarking.addTab(self.tab_5, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_17 = QtGui.QGridLayout(self.tab)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.mpl_memberscount = MplWidget(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl_memberscount.sizePolicy().hasHeightForWidth())
        self.mpl_memberscount.setSizePolicy(sizePolicy)
        self.mpl_memberscount.setObjectName("mpl_memberscount")
        self.gridLayout_17.addWidget(self.mpl_memberscount, 0, 0, 1, 1)
        self.tabWidget_adminmarking.addTab(self.tab, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.comboBox_viewtabledept = QtGui.QComboBox(self.tab_3)
        self.comboBox_viewtabledept.setObjectName("comboBox_viewtabledept")
        self.gridLayout_4.addWidget(self.comboBox_viewtabledept, 1, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem6, 1, 5, 1, 1)
        self.tableWidget = QtGui.QTableWidget(self.tab_3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout_4.addWidget(self.tableWidget, 0, 0, 1, 6)
        self.pushButton_commitchange = QtGui.QPushButton(self.tab_3)
        self.pushButton_commitchange.setObjectName("pushButton_commitchange")
        self.gridLayout_4.addWidget(self.pushButton_commitchange, 1, 4, 1, 1)
        self.pushButton_loadmemberdetails = QtGui.QPushButton(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_loadmemberdetails.sizePolicy().hasHeightForWidth())
        self.pushButton_loadmemberdetails.setSizePolicy(sizePolicy)
        self.pushButton_loadmemberdetails.setObjectName("pushButton_loadmemberdetails")
        self.gridLayout_4.addWidget(self.pushButton_loadmemberdetails, 1, 3, 1, 1)
        self.checkBox_inactivememebrs = QtGui.QCheckBox(self.tab_3)
        self.checkBox_inactivememebrs.setObjectName("checkBox_inactivememebrs")
        self.gridLayout_4.addWidget(self.checkBox_inactivememebrs, 1, 2, 1, 1)
        self.tabWidget_adminmarking.addTab(self.tab_3, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.groupBox_6 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 0, 891, 431))
        self.groupBox_6.setObjectName("groupBox_6")
        self.formLayoutWidget_2 = QtGui.QWidget(self.groupBox_6)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(0, 20, 321, 331))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_4 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.nameLabel = QtGui.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.nameLabel)
        self.nameLineEdit = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.nameLineEdit)
        self.englishNameLabel = QtGui.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.englishNameLabel.setFont(font)
        self.englishNameLabel.setObjectName("englishNameLabel")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.englishNameLabel)
        self.englishNameLineEdit = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.englishNameLineEdit.setObjectName("englishNameLineEdit")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.englishNameLineEdit)
        self.genderLabel = QtGui.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.genderLabel.setFont(font)
        self.genderLabel.setObjectName("genderLabel")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.genderLabel)
        self.comboBox_addmembergender = QtGui.QComboBox(self.formLayoutWidget_2)
        self.comboBox_addmembergender.setObjectName("comboBox_addmembergender")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.comboBox_addmembergender)
        self.deptLabel = QtGui.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.deptLabel.setFont(font)
        self.deptLabel.setObjectName("deptLabel")
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.deptLabel)
        self.comboBox_addmemberdept = QtGui.QComboBox(self.formLayoutWidget_2)
        self.comboBox_addmemberdept.setObjectName("comboBox_addmemberdept")
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.comboBox_addmemberdept)
        self.label_7 = QtGui.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_7)
        self.contactNum_lineEdit = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.contactNum_lineEdit.setObjectName("contactNum_lineEdit")
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.FieldRole, self.contactNum_lineEdit)
        self.pushButton_addmember = QtGui.QPushButton(self.formLayoutWidget_2)
        self.pushButton_addmember.setObjectName("pushButton_addmember")
        self.formLayout_4.setWidget(5, QtGui.QFormLayout.FieldRole, self.pushButton_addmember)
        self.formLayoutWidget = QtGui.QWidget(self.groupBox_6)
        self.formLayoutWidget.setGeometry(QtCore.QRect(330, 18, 521, 361))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_6 = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout_6.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_6.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_6.setContentsMargins(0, 0, 0, 0)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_5 = QtGui.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.calendarWidget_newmember_dob = QtGui.QCalendarWidget(self.formLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calendarWidget_newmember_dob.sizePolicy().hasHeightForWidth())
        self.calendarWidget_newmember_dob.setSizePolicy(sizePolicy)
        self.calendarWidget_newmember_dob.setCursor(QtCore.Qt.PointingHandCursor)
        self.calendarWidget_newmember_dob.setGridVisible(True)
        self.calendarWidget_newmember_dob.setVerticalHeaderFormat(QtGui.QCalendarWidget.NoVerticalHeader)
        self.calendarWidget_newmember_dob.setNavigationBarVisible(True)
        self.calendarWidget_newmember_dob.setObjectName("calendarWidget_newmember_dob")
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.calendarWidget_newmember_dob)
        self.label_6 = QtGui.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.calendarWidget_newmember_passing = QtGui.QCalendarWidget(self.formLayoutWidget)
        self.calendarWidget_newmember_passing.setCursor(QtCore.Qt.PointingHandCursor)
        self.calendarWidget_newmember_passing.setGridVisible(True)
        self.calendarWidget_newmember_passing.setVerticalHeaderFormat(QtGui.QCalendarWidget.NoVerticalHeader)
        self.calendarWidget_newmember_passing.setObjectName("calendarWidget_newmember_passing")
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.FieldRole, self.calendarWidget_newmember_passing)
        self.tabWidget_adminmarking.addTab(self.tab_4, "")
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.tab_6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.groupBox_9 = QtGui.QGroupBox(self.tab_6)
        self.groupBox_9.setObjectName("groupBox_9")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.formLayout_5 = QtGui.QFormLayout()
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_12 = QtGui.QLabel(self.groupBox_9)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_12)
        self.lineEdit_addnewevent = QtGui.QLineEdit(self.groupBox_9)
        self.lineEdit_addnewevent.setObjectName("lineEdit_addnewevent")
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_addnewevent)
        self.label_13 = QtGui.QLabel(self.groupBox_9)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_13)
        self.comboBox_addnewevent = QtGui.QComboBox(self.groupBox_9)
        self.comboBox_addnewevent.setObjectName("comboBox_addnewevent")
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.comboBox_addnewevent)
        self.label_14 = QtGui.QLabel(self.groupBox_9)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_14)
        self.calendarWidget_addevent = QtGui.QCalendarWidget(self.groupBox_9)
        self.calendarWidget_addevent.setGridVisible(True)
        self.calendarWidget_addevent.setVerticalHeaderFormat(QtGui.QCalendarWidget.NoVerticalHeader)
        self.calendarWidget_addevent.setNavigationBarVisible(True)
        self.calendarWidget_addevent.setObjectName("calendarWidget_addevent")
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.calendarWidget_addevent)
        self.label_18 = QtGui.QLabel(self.groupBox_9)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_18)
        self.timeEdit_starttimeaddnewevent = QtGui.QTimeEdit(self.groupBox_9)
        self.timeEdit_starttimeaddnewevent.setObjectName("timeEdit_starttimeaddnewevent")
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.FieldRole, self.timeEdit_starttimeaddnewevent)
        self.label_19 = QtGui.QLabel(self.groupBox_9)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.formLayout_5.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_19)
        self.timeEdit_endtimeaddnewevent = QtGui.QTimeEdit(self.groupBox_9)
        self.timeEdit_endtimeaddnewevent.setObjectName("timeEdit_endtimeaddnewevent")
        self.formLayout_5.setWidget(4, QtGui.QFormLayout.FieldRole, self.timeEdit_endtimeaddnewevent)
        self.pushButton_addnewevent = QtGui.QPushButton(self.groupBox_9)
        self.pushButton_addnewevent.setObjectName("pushButton_addnewevent")
        self.formLayout_5.setWidget(5, QtGui.QFormLayout.FieldRole, self.pushButton_addnewevent)
        self.horizontalLayout_7.addLayout(self.formLayout_5)
        self.horizontalLayout_10.addWidget(self.groupBox_9)
        self.groupBox_10 = QtGui.QGroupBox(self.tab_6)
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout_8 = QtGui.QFormLayout()
        self.formLayout_8.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_8.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_15 = QtGui.QLabel(self.groupBox_10)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.formLayout_8.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_15)
        self.calendarWidget_viewnewevent = QtGui.QCalendarWidget(self.groupBox_10)
        self.calendarWidget_viewnewevent.setGridVisible(True)
        self.calendarWidget_viewnewevent.setVerticalHeaderFormat(QtGui.QCalendarWidget.NoVerticalHeader)
        self.calendarWidget_viewnewevent.setObjectName("calendarWidget_viewnewevent")
        self.formLayout_8.setWidget(0, QtGui.QFormLayout.FieldRole, self.calendarWidget_viewnewevent)
        self.label_17 = QtGui.QLabel(self.groupBox_10)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.formLayout_8.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_17)
        self.tableWidget_viewevent = QtGui.QTableWidget(self.groupBox_10)
        self.tableWidget_viewevent.setObjectName("tableWidget_viewevent")
        self.tableWidget_viewevent.setColumnCount(0)
        self.tableWidget_viewevent.setRowCount(0)
        self.formLayout_8.setWidget(1, QtGui.QFormLayout.FieldRole, self.tableWidget_viewevent)
        self.pushButton_viewnewevent = QtGui.QPushButton(self.groupBox_10)
        self.pushButton_viewnewevent.setObjectName("pushButton_viewnewevent")
        self.formLayout_8.setWidget(2, QtGui.QFormLayout.FieldRole, self.pushButton_viewnewevent)
        self.verticalLayout_2.addLayout(self.formLayout_8)
        self.horizontalLayout_10.addWidget(self.groupBox_10)
        self.tabWidget_adminmarking.addTab(self.tab_6, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_7 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 10, 981, 431))
        self.groupBox_7.setObjectName("groupBox_7")
        self.formLayoutWidget_3 = QtGui.QWidget(self.groupBox_7)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(0, 20, 331, 231))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_7 = QtGui.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_7.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_7.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_7.setContentsMargins(0, 0, 0, 0)
        self.formLayout_7.setObjectName("formLayout_7")
        self.nameLabel_2 = QtGui.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.nameLabel_2.setFont(font)
        self.nameLabel_2.setObjectName("nameLabel_2")
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.LabelRole, self.nameLabel_2)
        self.englishNameLabel_2 = QtGui.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.englishNameLabel_2.setFont(font)
        self.englishNameLabel_2.setObjectName("englishNameLabel_2")
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.LabelRole, self.englishNameLabel_2)
        self.genderLabel_2 = QtGui.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.genderLabel_2.setFont(font)
        self.genderLabel_2.setObjectName("genderLabel_2")
        self.formLayout_7.setWidget(2, QtGui.QFormLayout.LabelRole, self.genderLabel_2)
        self.deptLabel_2 = QtGui.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.deptLabel_2.setFont(font)
        self.deptLabel_2.setObjectName("deptLabel_2")
        self.formLayout_7.setWidget(3, QtGui.QFormLayout.LabelRole, self.deptLabel_2)
        self.label_8 = QtGui.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout_7.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_8)
        self.lineEdit_profileconnum = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.lineEdit_profileconnum.setObjectName("lineEdit_profileconnum")
        self.formLayout_7.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_profileconnum)
        self.label_9 = QtGui.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.formLayout_7.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtGui.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName("label_10")
        self.formLayout_7.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_10)
        self.lineEdit_profiledob = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.lineEdit_profiledob.setObjectName("lineEdit_profiledob")
        self.formLayout_7.setWidget(5, QtGui.QFormLayout.FieldRole, self.lineEdit_profiledob)
        self.lineEdit_profilepassing = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.lineEdit_profilepassing.setObjectName("lineEdit_profilepassing")
        self.formLayout_7.setWidget(6, QtGui.QFormLayout.FieldRole, self.lineEdit_profilepassing)
        self.lineEdit_profilegender = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.lineEdit_profilegender.setObjectName("lineEdit_profilegender")
        self.formLayout_7.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_profilegender)
        self.comboBox_profilename = QtGui.QComboBox(self.formLayoutWidget_3)
        self.comboBox_profilename.setObjectName("comboBox_profilename")
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBox_profilename)
        self.comboBox_profiledept = QtGui.QComboBox(self.formLayoutWidget_3)
        self.comboBox_profiledept.setObjectName("comboBox_profiledept")
        self.formLayout_7.setWidget(3, QtGui.QFormLayout.FieldRole, self.comboBox_profiledept)
        self.lineEdit_profileenglishname = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.lineEdit_profileenglishname.setObjectName("lineEdit_profileenglishname")
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_profileenglishname)
        self.label_11 = QtGui.QLabel(self.groupBox_7)
        self.label_11.setGeometry(QtCore.QRect(340, 20, 221, 231))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("../unknown_profile.png"))
        self.label_11.setObjectName("label_11")
        self.label_personalpic = QtGui.QLabel(self.groupBox_7)
        self.label_personalpic.setGeometry(QtCore.QRect(350, 20, 231, 191))
        self.label_personalpic.setText("")
        self.label_personalpic.setPixmap(QtGui.QPixmap("../pyQt/unknown_profile.png"))
        self.label_personalpic.setObjectName("label_personalpic")
        self.tabWidget_adminmarking.addTab(self.tab_2, "")
        self.gridLayout_7.addWidget(self.tabWidget_adminmarking, 0, 0, 1, 1)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icon/admin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tab_widget_overall.addTab(self.tab_admin, icon3, "")
        self.pushButton_quit = QtGui.QPushButton(self.centralwidget)
        self.pushButton_quit.setGeometry(QtCore.QRect(10, 670, 121, 27))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.pushButton_quit.setFont(font)
        self.pushButton_quit.setObjectName("pushButton_quit")
        LWCAttendanceTaker.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(LWCAttendanceTaker)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 25))
        self.menubar.setObjectName("menubar")
        self.menuFlie = QtGui.QMenu(self.menubar)
        self.menuFlie.setObjectName("menuFlie")
        LWCAttendanceTaker.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(LWCAttendanceTaker)
        self.statusbar.setObjectName("statusbar")
        LWCAttendanceTaker.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(LWCAttendanceTaker)
        self.actionQuit.setObjectName("actionQuit")
        self.actionConnect = QtGui.QAction(LWCAttendanceTaker)
        self.actionConnect.setObjectName("actionConnect")
        self.actionConnect_to_home = QtGui.QAction(LWCAttendanceTaker)
        self.actionConnect_to_home.setObjectName("actionConnect_to_home")
        self.menuFlie.addAction(self.actionConnect)
        self.menuFlie.addAction(self.actionConnect_to_home)
        self.menuFlie.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFlie.menuAction())

        self.retranslateUi(LWCAttendanceTaker)
        self.tab_widget_overall.setCurrentIndex(1)
        self.tabWidget_statistics.setCurrentIndex(0)
        self.stackedWidget_ss.setCurrentIndex(0)
        self.stackedWidget_ws.setCurrentIndex(0)
        self.stackedWidget_fpm.setCurrentIndex(0)
        self.stackedWidget_ds.setCurrentIndex(0)
        self.tabWidget_adminmarking.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(LWCAttendanceTaker)

    def retranslateUi(self, LWCAttendanceTaker):
        LWCAttendanceTaker.setWindowTitle(QtGui.QApplication.translate("LWCAttendanceTaker", "LWC Attendance Taker", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("LWCAttendanceTaker", "Serial Port Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_refresh.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_connect.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_disconnect.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Disconnect", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("LWCAttendanceTaker", "Database Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_dbconnect.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Connect to database", None, QtGui.QApplication.UnicodeUTF8))
        self.databaseHostLabel.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Database Server Host IP", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_connecttohome.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Connect to 127.0.0.1", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_widget_overall.setTabText(self.tab_widget_overall.indexOf(self.tab_setup), QtGui.QApplication.translate("LWCAttendanceTaker", "Setup", None, QtGui.QApplication.UnicodeUTF8))
        self.label_welcome.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Welcome! Swipe ID for attendance!", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("LWCAttendanceTaker", "Identification", None, QtGui.QApplication.UnicodeUTF8))
        self.label_static_name.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_static_rfid.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "RFID:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_static_dept.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Dept:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_static_status.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Status:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("LWCAttendanceTaker", "What\'s up?", None, QtGui.QApplication.UnicodeUTF8))
        self.label_static_time.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_static_date.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Date:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_static_event.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Event:", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_widget_overall.setTabText(self.tab_widget_overall.indexOf(self.tab_attendance), QtGui.QApplication.translate("LWCAttendanceTaker", "Attendance", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_previous_graph_ss.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Previous", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_next_graph_ss.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_statistics.setTabText(self.tabWidget_statistics.indexOf(self.tab_sundayservice), QtGui.QApplication.translate("LWCAttendanceTaker", "Sunday Service", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_previous_graph_ws.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Previous", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_next_graph_ws.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_statistics.setTabText(self.tabWidget_statistics.indexOf(self.tab_wednesdayservice), QtGui.QApplication.translate("LWCAttendanceTaker", "Wednesday Service", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_previous_graph_fpm.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Previous", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_next_graph_fpm.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_statistics.setTabText(self.tabWidget_statistics.indexOf(self.tab_fridayprayer), QtGui.QApplication.translate("LWCAttendanceTaker", "Friday Prayer", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_previous_graph_ds.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Previous", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_next_graph_ds.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_statistics.setTabText(self.tabWidget_statistics.indexOf(self.tab_dawnservice), QtGui.QApplication.translate("LWCAttendanceTaker", "Dawn Service", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Month", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Year", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_plot.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Plot Graph", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_widget_overall.setTabText(self.tab_widget_overall.indexOf(self.tab_statistics), QtGui.QApplication.translate("LWCAttendanceTaker", "Service Statistics", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("LWCAttendanceTaker", "Attendance Marking", None, QtGui.QApplication.UnicodeUTF8))
        self.label_admintab_dept.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Dept", None, QtGui.QApplication.UnicodeUTF8))
        self.label_admintab_name.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_admintab_event.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Event Type", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Event Date", None, QtGui.QApplication.UnicodeUTF8))
        self.label_admintab_status.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_delete.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_submit.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Submit", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Picture", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_broadcast.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Broadcast", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_present.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Present", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("LWCAttendanceTaker", "Attendance View", None, QtGui.QApplication.UnicodeUTF8))
        self.attendeeLabel.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Attendee(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.eventLabel.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Event", None, QtGui.QApplication.UnicodeUTF8))
        self.dateLabel.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_viewatt.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "View!", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Summary", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Total Broadcast:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Total Present:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_adminmarking.setTabText(self.tabWidget_adminmarking.indexOf(self.tab_5), QtGui.QApplication.translate("LWCAttendanceTaker", "Admin Marking", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_adminmarking.setTabText(self.tabWidget_adminmarking.indexOf(self.tab), QtGui.QApplication.translate("LWCAttendanceTaker", "Members Count", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_commitchange.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Commit Changes", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_loadmemberdetails.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_inactivememebrs.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Inactive Members", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_adminmarking.setTabText(self.tabWidget_adminmarking.indexOf(self.tab_3), QtGui.QApplication.translate("LWCAttendanceTaker", "Edit Members\' Details", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("LWCAttendanceTaker", "Add New Member", None, QtGui.QApplication.UnicodeUTF8))
        self.nameLabel.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.englishNameLabel.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "English Name", None, QtGui.QApplication.UnicodeUTF8))
        self.genderLabel.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Gender", None, QtGui.QApplication.UnicodeUTF8))
        self.deptLabel.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Dept", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Contact Num", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_addmember.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Add new member!", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Date of Birth", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Passing Date", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_adminmarking.setTabText(self.tabWidget_adminmarking.indexOf(self.tab_4), QtGui.QApplication.translate("LWCAttendanceTaker", "Add New Members", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setTitle(QtGui.QApplication.translate("LWCAttendanceTaker", "New Event Details", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Time Start", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Time End", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_addnewevent.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Add new event!", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_10.setTitle(QtGui.QApplication.translate("LWCAttendanceTaker", "View Event", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "List", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_viewnewevent.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_adminmarking.setTabText(self.tabWidget_adminmarking.indexOf(self.tab_6), QtGui.QApplication.translate("LWCAttendanceTaker", "Add New Event", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("LWCAttendanceTaker", "Profile", None, QtGui.QApplication.UnicodeUTF8))
        self.nameLabel_2.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.englishNameLabel_2.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "English Name", None, QtGui.QApplication.UnicodeUTF8))
        self.genderLabel_2.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Gender", None, QtGui.QApplication.UnicodeUTF8))
        self.deptLabel_2.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Dept", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Contact Num", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Date of Birth", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Passing Date", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_adminmarking.setTabText(self.tabWidget_adminmarking.indexOf(self.tab_2), QtGui.QApplication.translate("LWCAttendanceTaker", "Personal Profile", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_widget_overall.setTabText(self.tab_widget_overall.indexOf(self.tab_admin), QtGui.QApplication.translate("LWCAttendanceTaker", "Administration", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_quit.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFlie.setTitle(QtGui.QApplication.translate("LWCAttendanceTaker", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConnect.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConnect_to_home.setText(QtGui.QApplication.translate("LWCAttendanceTaker", "Connect to home", None, QtGui.QApplication.UnicodeUTF8))

from mplwidget import MplWidget
